server:
   port: 8093
   
#Conextion to Mongo DB
spring:
  application:
    name: product_service
  data:
    mongodb:
      uri: mongodb://localhost:27017/PRODUCT
         
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposre:
        include: "*"