server:
   port: 8090
   
#Conextion to Mongo DB
spring:
  application:
    name: customer_service
  data:
    mongodb:
#      uri: mongodb://localhost:27017/CUSTOMER
      uri: mongodb://admin:password@mongodb-service:27017/CUSTOMER?authSource=admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://docker-registry-service:8761/eureka/
management:
  endpoints:
    web:
      exposre:
        include: "*"
        
resilience4j.circuitbreaker:
    instances:
        customer-service:
            failureRateThreshold: 40
            waitDurationInOpenState: 4s
            minimumNumberOfCalls: 5

resilience4j.timelimiter:
    instances:
        customer-service:
            timeoutDuration: 2s
            cancelRunningFuture: true