version: '3.8'
services:
  gateway_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-gateway-service
    restart: always
    ports:
      - 8085:8085
    networks:
      network_bank:
        aliases:
          - net_cloud
networks:
  network_bank:
    name: net_cloud
    external: true