version: '3.8'
services:
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-config-server
    restart: always
    ports:
      - 8888:8888
    networks:
      network_bank:
        aliases:
          - net_cloud
networks:
  network_bank:
    name: net_cloud
    external: true